name: flutter_avif_linux
description: Linux implementation for flutter_avif.
version: 1.4.0
repository: https://github.com/yekeskin/flutter_avif/tree/main/flutter_avif_linux

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_avif_platform_interface:
    path: ../flutter_avif_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  
flutter:
  plugin:
    implements: flutter_avif
    platforms:
      linux:
        pluginClass: FlutterAvifLinuxPlugin
        dartPluginClass: FlutterAvifLinux
