// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.3.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

abstract class FlutterAvif {
  Future<Frame> decodeSingleFrameImage(
      {required Uint8List avifBytes, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kDecodeSingleFrameImageConstMeta;

  Future<AvifInfo> initMemoryDecoder(
      {required String key, required Uint8List avifBytes, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kInitMemoryDecoderConstMeta;

  Future<bool> resetDecoder({required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kResetDecoderConstMeta;

  Future<bool> disposeDecoder({required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kDisposeDecoderConstMeta;

  Future<Frame> getNextFrame({required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetNextFrameConstMeta;

  Future<Uint8List> encodeAvif(
      {required int width,
      required int height,
      required int speed,
      required int maxThreads,
      required int timescale,
      required int maxQuantizer,
      required int minQuantizer,
      required int maxQuantizerAlpha,
      required int minQuantizerAlpha,
      required List<EncodeFrame> imageSequence,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kEncodeAvifConstMeta;
}

class AvifInfo {
  final int width;
  final int height;
  final int imageCount;
  final double duration;

  const AvifInfo({
    required this.width,
    required this.height,
    required this.imageCount,
    required this.duration,
  });
}

class EncodeFrame {
  final Uint8List data;
  final int durationInTimescale;

  const EncodeFrame({
    required this.data,
    required this.durationInTimescale,
  });
}

class Frame {
  final Uint8List data;
  final double duration;
  final int width;
  final int height;

  const Frame({
    required this.data,
    required this.duration,
    required this.width,
    required this.height,
  });
}

class FlutterAvifImpl {}

class FlutterAvifPlatform {}

class FlutterAvifWire {}
