// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `avif_info.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:models.AvifInfo)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct AvifInfo {
    // message fields
    // @@protoc_insertion_point(field:models.AvifInfo.width)
    pub width: u32,
    // @@protoc_insertion_point(field:models.AvifInfo.height)
    pub height: u32,
    // @@protoc_insertion_point(field:models.AvifInfo.image_count)
    pub image_count: u32,
    // @@protoc_insertion_point(field:models.AvifInfo.duration)
    pub duration: f64,
    // special fields
    // @@protoc_insertion_point(special_field:models.AvifInfo.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a AvifInfo {
    fn default() -> &'a AvifInfo {
        <AvifInfo as ::protobuf::Message>::default_instance()
    }
}

impl AvifInfo {
    pub fn new() -> AvifInfo {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "width",
            |m: &AvifInfo| { &m.width },
            |m: &mut AvifInfo| { &mut m.width },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "height",
            |m: &AvifInfo| { &m.height },
            |m: &mut AvifInfo| { &mut m.height },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "image_count",
            |m: &AvifInfo| { &m.image_count },
            |m: &mut AvifInfo| { &mut m.image_count },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "duration",
            |m: &AvifInfo| { &m.duration },
            |m: &mut AvifInfo| { &mut m.duration },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<AvifInfo>(
            "AvifInfo",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for AvifInfo {
    const NAME: &'static str = "AvifInfo";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.width = is.read_uint32()?;
                },
                16 => {
                    self.height = is.read_uint32()?;
                },
                24 => {
                    self.image_count = is.read_uint32()?;
                },
                33 => {
                    self.duration = is.read_double()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.width != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.width);
        }
        if self.height != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.height);
        }
        if self.image_count != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.image_count);
        }
        if self.duration != 0. {
            my_size += 1 + 8;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.width != 0 {
            os.write_uint32(1, self.width)?;
        }
        if self.height != 0 {
            os.write_uint32(2, self.height)?;
        }
        if self.image_count != 0 {
            os.write_uint32(3, self.image_count)?;
        }
        if self.duration != 0. {
            os.write_double(4, self.duration)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> AvifInfo {
        AvifInfo::new()
    }

    fn clear(&mut self) {
        self.width = 0;
        self.height = 0;
        self.image_count = 0;
        self.duration = 0.;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static AvifInfo {
        static instance: AvifInfo = AvifInfo {
            width: 0,
            height: 0,
            image_count: 0,
            duration: 0.,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for AvifInfo {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("AvifInfo").unwrap()).clone()
    }
}

impl ::std::fmt::Display for AvifInfo {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AvifInfo {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0favif_info.proto\x12\x06models\"u\n\x08AvifInfo\x12\x14\n\x05width\
    \x18\x01\x20\x01(\rR\x05width\x12\x16\n\x06height\x18\x02\x20\x01(\rR\
    \x06height\x12\x1f\n\x0bimage_count\x18\x03\x20\x01(\rR\nimageCount\x12\
    \x1a\n\x08duration\x18\x04\x20\x01(\x01R\x08durationJ\x90\x02\n\x06\x12\
    \x04\0\0\t\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\
    \x02\0\x0f\n\n\n\x02\x04\0\x12\x04\x04\0\t\x01\n\n\n\x03\x04\0\x01\x12\
    \x03\x04\x08\x10\n\x0b\n\x04\x04\0\x02\0\x12\x03\x05\x02\x13\n\x0c\n\x05\
    \x04\0\x02\0\x05\x12\x03\x05\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\
    \x05\t\x0e\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x05\x11\x12\n\x0b\n\x04\
    \x04\0\x02\x01\x12\x03\x06\x02\x14\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\
    \x06\x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x06\t\x0f\n\x0c\n\x05\
    \x04\0\x02\x01\x03\x12\x03\x06\x12\x13\n\x0b\n\x04\x04\0\x02\x02\x12\x03\
    \x07\x02\x19\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x07\x02\x08\n\x0c\n\
    \x05\x04\0\x02\x02\x01\x12\x03\x07\t\x14\n\x0c\n\x05\x04\0\x02\x02\x03\
    \x12\x03\x07\x17\x18\n\x0b\n\x04\x04\0\x02\x03\x12\x03\x08\x02\x16\n\x0c\
    \n\x05\x04\0\x02\x03\x05\x12\x03\x08\x02\x08\n\x0c\n\x05\x04\0\x02\x03\
    \x01\x12\x03\x08\t\x11\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\x08\x14\x15\
    b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(AvifInfo::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
