// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `encode_frame.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:models.EncodeFrame)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct EncodeFrame {
    // message fields
    // @@protoc_insertion_point(field:models.EncodeFrame.data)
    pub data: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:models.EncodeFrame.duration_in_timescale)
    pub duration_in_timescale: u32,
    // special fields
    // @@protoc_insertion_point(special_field:models.EncodeFrame.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a EncodeFrame {
    fn default() -> &'a EncodeFrame {
        <EncodeFrame as ::protobuf::Message>::default_instance()
    }
}

impl EncodeFrame {
    pub fn new() -> EncodeFrame {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "data",
            |m: &EncodeFrame| { &m.data },
            |m: &mut EncodeFrame| { &mut m.data },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "duration_in_timescale",
            |m: &EncodeFrame| { &m.duration_in_timescale },
            |m: &mut EncodeFrame| { &mut m.duration_in_timescale },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<EncodeFrame>(
            "EncodeFrame",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for EncodeFrame {
    const NAME: &'static str = "EncodeFrame";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.data = is.read_bytes()?;
                },
                16 => {
                    self.duration_in_timescale = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.data);
        }
        if self.duration_in_timescale != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.duration_in_timescale);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.data.is_empty() {
            os.write_bytes(1, &self.data)?;
        }
        if self.duration_in_timescale != 0 {
            os.write_uint32(2, self.duration_in_timescale)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> EncodeFrame {
        EncodeFrame::new()
    }

    fn clear(&mut self) {
        self.data.clear();
        self.duration_in_timescale = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static EncodeFrame {
        static instance: EncodeFrame = EncodeFrame {
            data: ::std::vec::Vec::new(),
            duration_in_timescale: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for EncodeFrame {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("EncodeFrame").unwrap()).clone()
    }
}

impl ::std::fmt::Display for EncodeFrame {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for EncodeFrame {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x12encode_frame.proto\x12\x06models\"U\n\x0bEncodeFrame\x12\x12\n\x04\
    data\x18\x01\x20\x01(\x0cR\x04data\x122\n\x15duration_in_timescale\x18\
    \x02\x20\x01(\rR\x13durationInTimescaleJ\xa2\x01\n\x06\x12\x04\0\0\x07\
    \x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x02\0\x0f\n\
    \n\n\x02\x04\0\x12\x04\x04\0\x07\x01\n\n\n\x03\x04\0\x01\x12\x03\x04\x08\
    \x13\n\x0b\n\x04\x04\0\x02\0\x12\x03\x05\x02\x11\n\x0c\n\x05\x04\0\x02\0\
    \x05\x12\x03\x05\x02\x07\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x05\x08\x0c\
    \n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x05\x0f\x10\n\x0b\n\x04\x04\0\x02\
    \x01\x12\x03\x06\x02#\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x06\x02\x08\
    \n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x06\t\x1e\n\x0c\n\x05\x04\0\x02\
    \x01\x03\x12\x03\x06!\"b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(EncodeFrame::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
